### ISSUE TITLE
Error: RoyalMod caught error from FS22_SeeBales (3.0.0.1)

### ISSUE THREAD

**Issue by mrPassion78** [Mmtrx/FS22_SeeBales#1]
hi there, i got an error from your mod while unloading fresh wrapped bales.
i was using the poetinger baler+wrapper combi, and when the bale is wrapped, and it gets unloaded, then the error pops up.
i will attach my log file..
I was also experimenting with a mod while that throws an error to, but its unrelated to your mod.

And thnx a whole lot for bringing this mod into fs22, it makes it alot more easy on 4x maps to find the bales back at night on a 25HA field ..:
[log.txt](https://github.com/Mmtrx/FS22_SeeBales/files/9034639/log.txt)
TIP: the error is  at the bottom of the logfile.:
2022-07-03 13:26   Error: RoyalMod caught error from FS22_SeeBales (3.0.0.1)
2022-07-03 13:26   Error: C:/Users/pasca/Documents/My Games/FarmingSimulator2022/mods/GAMEPLAY FS22/FS22_SeeBales/scripts/helper.lua:140: attempt to index a nil value

**Comment by Mmtrx** [comment]
Hi,
thanks for reporting this. A hotfix is available [here](https://github.com/Mmtrx/FS22_SeeBales/releases/tag/v3.0.0.2)

**Comment by mrPassion78** [comment]
owesome, and thnx for the quick fix.. :D i will close this now.
