### ISSUE TITLE
after refueling GUI disapears

### ISSUE THREAD

**Issue by stk2008** [Mmtrx/FS22_SeeBales#5]
Hi, I have an issue with See Bales versions 3.0.0.2 and 3.0.0.1.

Once refuelling has been completed, the GUI disappears, and I have to exit to main menu again and reload for it to show back up.

before refuelling: https://i.imgur.com/hdR2Ybi.jpeg

after refuelling (pressing r) https://i.imgur.com/9DSSlOv.jpeg

thanks in advance :)

**Comment by Gordon-Dry** [comment]
How about some log for a clear insight of what's potentially happening?

**Comment by Mmtrx** [comment]
Expired.
